# Generated by Django 5.2.8 on 2025-11-21 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('revision_pages', models.IntegerField()),
                ('new_work_pages', models.IntegerField()),
                ('starts_at', models.TimeField()),
                ('ends_at', models.TimeField()),
            ],
        ),
    ]
