# Generated by Django 5.2.8 on 2025-11-21 22:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('stage', models.IntegerField()),
                ('initial_page', models.IntegerField()),
                ('final_page', models.IntegerField()),
                ('revision', models.IntegerField(blank=True, null=True)),
                ('last_word', models.CharField(max_length=50)),
                ('dictatin', models.IntegerField()),
                ('lesson_check', models.IntegerField()),
                ('initials', models.CharField(max_length=50)),
                ('supervisor', models.CharField(max_length=50)),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classes.schoolclass')),
            ],
        ),
    ]
