# Generated by Django 5.2.8 on 2025-11-21 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_classsheet'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classsheet',
            old_name='dictatin',
            new_name='dictation',
        ),
    ]
