# Generated by Django 5.2.8 on 2025-11-21 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0003_rename_dictatin_classsheet_dictation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classsheet',
            name='supervisor',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
