# Generated by Django 5.2.8 on 2025-11-21 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0004_alter_classsheet_supervisor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classsheet',
            name='lesson_check',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
