# Generated by Django 5.2.8 on 2025-11-21 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0005_alter_classsheet_lesson_check'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classsheet',
            name='dictation',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
