# Generated by Django 5.2.8 on 2025-11-22 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0006_alter_classsheet_dictation'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolclass',
            name='days',
            field=models.JSONField(default=list),
        ),
    ]
