# Generated by Django 5.2.8 on 2025-11-22 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0007_schoolclass_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolclass',
            name='new_work_pages',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='schoolclass',
            name='revision_pages',
            field=models.FloatField(),
        ),
    ]
