# Generated by Django 5.2.8 on 2025-11-22 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0008_alter_schoolclass_new_work_pages_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classsheet',
            old_name='revision',
            new_name='reading',
        ),
    ]
