# Generated by Django 5.2.8 on 2025-11-22 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0009_rename_revision_classsheet_reading'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schoolclass',
            options={'verbose_name': 'Class', 'verbose_name_plural': 'Classes'},
        ),
    ]
