# Generated by Django 5.2.8 on 2025-11-22 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0010_alter_schoolclass_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schoolclass',
            options={'verbose_name': 'class', 'verbose_name_plural': 'classes'},
        ),
    ]
